version: '3.7'

services:
    dbt:
        image: "ghcr.io/dbt-labs/dbt-postgres:1.3.1"
        volumes:
            - "./:/usr/app/dbt"
            - "./profiles.yml:/root/.dbt/profiles.yml"
        command: "run --vars='{\"table_prefix\":\"_77e9ae01\",\"timestamp\":\"1674902643.235171\",\"workspace_id\":\"7d78ac57-fdba-4ff0-af4f-d9199fad2d80\",\"integration_id\":\"77e9ae01-35b1-4ed9-b445-3025c635555d\"}'"
        networks:
            default:
            db-bridge:
                aliases: 
                    - db
networks:
    db-bridge:
        name: db-bridge
        driver: bridge
